# Generated by Django 3.1.3 on 2021-10-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='detail',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
