# Generated by Django 3.1.3 on 2021-11-03 04:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_announcement_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
    ]
