# Generated by Django 3.1.3 on 2021-03-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('hyperlink', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
