# Generated by Django 3.1.3 on 2021-11-03 04:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_auto_20211102_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
