# Generated by Django 3.1.3 on 2021-03-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
