# Generated by Django 3.1.3 on 2021-11-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_auto_20211102_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event_files',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
