# Generated by Django 3.1.3 on 2021-03-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
