# Generated by Django 3.1.3 on 2021-11-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_announcement_event_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='event_files',
            new_name='announcement_files',
        ),
    ]
