# Generated by Django 3.1.3 on 2021-12-08 16:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_auto_20211103_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('call_to_action', models.CharField(blank=True, max_length=250, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('section_1_title', models.CharField(max_length=200)),
                ('section_1_body', ckeditor.fields.RichTextField(blank=True, max_length=600, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('section_2_title', models.CharField(max_length=200)),
                ('section_2_body', ckeditor.fields.RichTextField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
