# Generated by Django 3.1.3 on 2021-12-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='call_to_action_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
