# Generated by Django 3.1.3 on 2021-03-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_event_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
