# Generated by Django 3.1.3 on 2021-12-08 17:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_page_call_to_action_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='section_1_body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='section_2_body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
    ]
