# Generated by Django 3.1.3 on 2021-03-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_reading_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='title',
        ),
        migrations.AddField(
            model_name='reading',
            name='gospel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='reading_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='reading_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
