# Generated by Django 3.1.3 on 2021-03-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_auto_20210311_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
