# Generated by Django 3.1.3 on 2022-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_auto_20211208_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='section_1_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='section_2_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
