# Generated by Django 3.1.3 on 2021-03-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_event_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='gospel_passage',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='reading_1_passage',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='reading_2_passage',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
