# Generated by Django 3.1.3 on 2021-03-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_auto_20210321_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
