# Generated by Django 3.1.3 on 2022-01-05 21:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_auto_20220105_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
