# Generated by Django 3.1.3 on 2021-03-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0012_event_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='files',
        ),
        migrations.AddField(
            model_name='event',
            name='event_files',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
