# Generated by Django 3.1.3 on 2021-03-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_auto_20210326_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='details2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
