# Generated by Django 4.2.5 on 2023-11-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_photoalbum_alter_announcement_announcement_files_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoalbum',
            options={'ordering': ['-start_date'], 'verbose_name': 'Photo Album', 'verbose_name_plural': 'Photo Albums'},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='file',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
