# Generated by Django 4.2.5 on 2023-12-13 15:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0015_alter_announcement_id_alter_banner_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_files',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
