# Generated by Django 4.2.5 on 2024-02-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0016_alter_event_cover_image_alter_event_event_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
